name: denv_drawing_canvas
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.2.1
  go_router: ^12.0.1
  equatable: ^2.0.5
  freezed: ^2.4.5
  
  riverpod_generator: ^2.3.5
  json_annotation: ^4.8.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/color_wheel.svg

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch